jdbc:
  driveClassName: com.mysql.cj.jdbc.Driver
  user: root
  pass: 123456

user:
  jdbc:
    url: jdbc:mysql://localhost:3306/user_service

product:
  jdbc:
    url: jdbc:mysql://localhost:3306/product_service

#hibernate
hibernate:
  show_sql: true
  dialect: org.hibernate.dialect.MySQL5Dialect
  hbm2ddl:
    auto: validate
  cache:
    use_second_level_cache: false
    use_query_cache: false

#server.port
server:
  port: 8081
